
#Build phase

FROM node:alpine as builder
WORKDIR '/app'
COPY package.json .
RUN npm install
#copy all source code
COPY . .
RUN npm run build


#RUN phase
FROM nginx
COPY --from=builder /app/build /usr/share/nginx/html
